### ISSUE TITLE
Does not function like JSON.stringify

### ISSUE THREAD

**Issue by s0kil** [LuKks/like-json#3]
## When trying to stringify an object like this:
```javascript
{
  query: 'query($id:ID!){product(id:$id){id name slug main_image{href}}}',
  variables: '{"id":"2f596919-dfa1-4fe0-b134-e703b2ffb51d"}'
}
```

Here the result of `like-json.stringify`:
```javascript
{"query":"query($id:ID!){product(id:$id){id name slug main_image{href}}}"}
```

and here is `JSON.stringify`:
```javascript
{"query":"query($id:ID!){product(id:$id){id name slug main_image{href}}}",
"variables":"{\"id\":\"2f596919-dfa1-4fe0-b134-e703b2ffb51d\"}"}
```

### Is this the intended behavior?

**Comment by LuKks** [comment]
No. When you use like.stringify function, internally there is a cache by id. So you are using the same id thus the same pre-compiled function for different structs.
The .stringify function exists to be easy changing from JSON to like. Notice that you have a bit more performance using directly the pre-compiled function.

I will let you an example.
```js
var user = { username: 's0kil' };

console.log(JSON.stringify(user)); //{"username":"s0kil"}
console.log(like.stringify(user, 1)); //{"username":"s0kil"}

//re-using the previous id (wrong because shapes are differents)
var item = { status: 'sent' };
console.log(like.stringify(item, 1)); //{"username":"undefined"}

//and here using a new id (correct because is a new shape)
console.log(like.stringify(item, 2)); //{"status":"sent"}
 ```
I hope I was clear.

In addition to the above, later with your object you will have troubles with encoding.
```js
var result = {
  query: 'query($id:ID!){}',
  variables: '{"id":"2f59"}'
};

//notice the slashes
console.log(JSON.stringify(result));
//{"query":"query($id:ID!){}","variables":"{\"id\":\"2f59\"}"}

//notice the missed slashes!
console.log(like.stringify(result, 3));
//{"query":"query($id:ID!){}","variables":"{"id":"2f59"}"}

//it pre-compiles with encoding (lower performance)
console.log(like.stringify(result, 4, { encode: true }));
//{"query":"query($id:ID!){}","variables":"{\"id\":\"2f59\"}"}
 ```

You can avoid it if you have "variables" in an object, so there is no quotes to encode. Just to be clear:
```js
var result = {
  query: 'query($id:ID!){}',
  variables: { id: '2f59' }
};
 ```

Yes, I know. You are thinking "aahggg, too much things for stringify" but "like" is just a simple concatenation. From there the name, "it's like" so it's normal have a trade-off.
I did this library because was needed in my framework (no public because is not finished and I have little time) and it integrates excellent but even the framework pretend to use both (JSON and like), normally JSON for development and like for production.
By the way, now I'm thinking that I forgot add documentation about encoding.

Really happy to see that some people use it :)

**Comment by s0kil** [comment]
@LuKks Thank You for detailed explanation, going to give it a go.
