### ISSUE TITLE
Hash Object Structure Internally For Reuse

### ISSUE THREAD

**Issue by s0kil** [LuKks/like-json#4]
With the current API maintaining Id's for different object structures could be abstracted to provide the behaviour of `JSON.stringify` without any overhead.

## Proposal
When using the `like.stringify({ msg: 'Created.' })` function without providing an ID, we could create an ID internally based on the object structure.
```js
const obj1 = {first: 'Lucas', last: 'Barrena'};
hashProps(obj1) // 1
const obj2 = {first: 'Daniel', last: 'Sokil'};
hashProps(obj2) // 1
const obj3 = {x: -19.78, y: 45.78};
hashProps(obj3) // 2
```

If an object has an depth larger than 2 and has multiple top-level keys
```js
const object = {
  one: {
    a: {}
  },
  two: {
    b: {}
  },
  three: {
    c: {}
  }
};
```
we could iterate recursively over every top-level object in parallel, in order to preserve the current performance of the `like-json` API.

## Ref
[deep-keys](https://github.com/a8m/deep-keys)

**Comment by s0kil** [comment]
This could be implemented in a separate package on top of `like-json`, but that would decrease performance substantially, since `like-json` already iterates the object properties.

**Comment by LuKks** [comment]
I like the idea.
The problem would be that every time that you call ```like.stringify``` it will need to re-generate the id and it will decrease the performance more than just the current way (cache with simple condition) inside of ```like.stringify```.

But still a great idea because if someone want perfect performance should use ```like.json``` and if want a quick change to gain performance can use ```like.stringify```, with your proposal almost without changes.

So, when I have time I will do something and we can see how it's going.
I want to say again that is a great idea because sometimes can be annoy handling too much ids, thanks!

**Comment by LuKks** [comment]
Woah, it was a long time, I was busy with other libraries where feedback is welcome too :)

I already did this feature, **`like.stringify` with automatic id based on input but it had twice lower performance than `JSON.stringify`**.

By the way, it can't be same as deep-keys because we need to know the type of value:
```js
{ password: 'hwy' }
{ password: 111 }
```
`deep-keys` will result in `['password']` in both cases.

I had done something like this:
```js
getStructId('Daniel'); // s
getStructId({ last: 'Sokil' }); // =o,last=s,
```
The first "=o" is because the base input is an object.

But this is very slow, I will stick with manual id for now.
Besides, the real perfect performance is on `like.json`.

**Comment by s0kil** [comment]
@LuKks https://github.com/lukeed/klona

**Comment by s0kil** [comment]
@LuKks I have thought about this some more, and maybe there is a solution.
Instead of checking the (keys, values) of the `obj` being encoded, we could contain an reference to the object itself, since every object is unique in memory even if the keys and values are the same.

https://github.com/s0kil/like-json/blob/master/index.js#L159-L183

**Comment by LuKks** [comment]
Looks very dangerous becasue that is keeping every object alive and it doesn't allow the garbage collector to remove them, right?
Also, normally when you encode an object is always a new object, so it's not an ideal approach.
